#!/usr/bin/env bash
# Portable unit tests of the Linux workspace helpers. Runs on macOS and Linux.
# Drives shipped sources under linux/src — not reimplementations.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTDIR="${TMPDIR:-/tmp}/ft-linux-test-$$"
mkdir -p "$OUTDIR"
CC="${CC:-cc}"
CFLAGS="-O2 -Wall -Wextra -I $ROOT/linux/src"

CORE=(
  "$ROOT/linux/src/util.c"
  "$ROOT/linux/src/path.c"
  "$ROOT/linux/src/session.c"
  "$ROOT/linux/src/split.c"
  "$ROOT/linux/src/layout.c"
  "$ROOT/linux/src/remote.c"
  "$ROOT/linux/src/prefs.c"
  "$ROOT/linux/src/command.c"
  "$ROOT/linux/src/model.c"
  "$ROOT/linux/src/control.c"
  "$ROOT/linux/src/sel.c"
  "$ROOT/linux/src/desktop.c"
)

run_test() {
  local name="$1"
  shift
  local bin="$OUTDIR/$name"
  $CC $CFLAGS -o "$bin" "$@"
  "$bin"
}

run_test test_session "$ROOT/linux/tests/test_session.c" "$ROOT/linux/src/session.c"
run_test test_path "$ROOT/linux/tests/test_path.c" "$ROOT/linux/src/path.c" "$ROOT/linux/src/util.c"
run_test test_split "$ROOT/linux/tests/test_split.c" "$ROOT/linux/src/split.c" "$ROOT/linux/src/util.c"
run_test test_layout "$ROOT/linux/tests/test_layout.c" "$ROOT/linux/src/layout.c" "$ROOT/linux/src/split.c" "$ROOT/linux/src/path.c" "$ROOT/linux/src/util.c"
run_test test_remote "$ROOT/linux/tests/test_remote.c" "$ROOT/linux/src/remote.c" "$ROOT/linux/src/path.c" "$ROOT/linux/src/util.c"
run_test test_prefs "$ROOT/linux/tests/test_prefs.c" "$ROOT/linux/src/prefs.c" "$ROOT/linux/src/command.c" "$ROOT/linux/src/util.c"
run_test test_control "$ROOT/linux/tests/test_control.c" "${CORE[@]}"
run_test test_model "$ROOT/linux/tests/test_model.c" "${CORE[@]}"
run_test test_sel "$ROOT/linux/tests/test_sel.c" "$ROOT/linux/src/sel.c" "$ROOT/linux/src/command.c" "$ROOT/linux/src/util.c"
run_test test_folder "$ROOT/linux/tests/test_folder.c" "${CORE[@]}"
run_test test_desktop "$ROOT/linux/tests/test_desktop.c" "$ROOT/linux/src/desktop.c" "$ROOT/linux/src/command.c" "$ROOT/linux/src/util.c"

rm -rf "$OUTDIR"

DESKTOP="$ROOT/linux/share/applications/com.davidsolheim.futuraterm.desktop"
test -f "$DESKTOP"
grep -q '^Name=FuturaTerm$' "$DESKTOP"
grep -q '^Exec=futuraterm$' "$DESKTOP"
grep -q '^Categories=System;TerminalEmulator;$' "$DESKTOP"
grep -q '^StartupWMClass=com.davidsolheim.futuraterm$' "$DESKTOP"
test -f "$ROOT/linux/share/icons/hicolor/256x256/apps/com.davidsolheim.futuraterm.png"
test -f "$ROOT/linux/packaging/install.sh"
grep -q 'share/applications' "$ROOT/linux/packaging/install.sh"
grep -q -- '--noconfirm' "$ROOT/linux/packaging/install.sh"
grep -q -- '--needed' "$ROOT/linux/packaging/install.sh"
grep -q 'MISE_YES' "$ROOT/linux/packaging/install.sh"
! grep -q '^DBusActivatable=' "$DESKTOP"
! grep -E -q '(^|[[:space:]])read[[:space:]]' "$ROOT/linux/packaging/install.sh"

APP="$ROOT/linux/src/app.c"
test -f "$APP"
grep -q 'show_palette' "$APP"
grep -q 'Command Palette' "$APP"
grep -q 'gtk_stack_add_titled.*[Gg]eneral' "$APP"
grep -q 'gtk_stack_add_titled.*[Pp]rojects' "$APP"
grep -q 'gtk_stack_add_titled.*[Aa]ppearance' "$APP"
grep -q 'gtk_stack_add_titled.*[Qq]uick' "$APP"
grep -q 'gtk_stack_add_titled.*[Kk]eymaps' "$APP"
grep -q 'toggle_quick' "$APP"
grep -F -q 'Local Folder…' "$APP"
grep -F -q 'Remote Machine…' "$APP"
grep -q 'viewDesktop' "$ROOT/linux/src/command.c"
grep -q 'view_desktop' "$APP"
grep -F -q 'New Folder' "$APP"
grep -q 'gtk_menu_button_set_label.*"New Project"' "$APP"
grep -q 'gtk_button_new_with_label("Sessions")' "$APP"
grep -q 'gtk_window_set_title.*"Sessions"' "$APP"
